### PR TITLE
fix isPomFile method NPE;add feature: support run goal in nearby pom dir

### PR DESCRIPTION
**Pull request by ileler**
add feature:
    support exec mvn cmd in pom dir closeat focus file, and on/off settings
fix isPomFile function sometime throw NullPointException .

### CODE REVIEW

**Comment by krasa** [comment]
I thought that org.jetbrains.idea.maven.project.MavenProject#getDirectory gets you the closest pom, how come you need to do that manually?

**Comment by krasa** [comment]
This is how you do it:
image
->https://github.com/krasa/MavenHelper/commit/c480f83acff4a9017ef15e12ab2524355425fc8c

And wouldn't this be better?
https://github.com/krasa/MavenHelper/commit/cf990310b32d29859cb9f524b723c003440d053f

**Comment by ileler** [comment]
qq 20171015182051

**Comment by ileler** [comment]
@krasa i don't good at Aesthetics

**Comment by krasa** [comment]
Works fine for me. 
image

but your feature would be needed if the module was not imported/was deleted - which is not a normal thing:
image

**Comment by ileler** [comment]
@krasa  yes.due to our company,this is a regular action for that situation.we are be badly in need of this feature.

**Comment by krasa** [comment]
Ok. All done, you can update.

**Comment by ileler** [comment]
Ok. thinks.

**Pull request merged**
