### PR TITLE
Option to resolve artifacts from workspace

### PR DESCRIPTION
**Pull request by nitramek**
* Works for not configured actions, there is option for them in the configuration dialog
* Testable with multi module project, where one depends on another.
  * _Application_ module depends on _Dependency_ module
  * make changes to _Dependency_ module, for example add parameter
  * build project
  * use maven runner for compiling _Application_  module, it should compile without installing the changed dependency.

### CODE REVIEW

**Comment by krasa** [comment]
Shouldn't it be rather "Resolve Workspace artifacts" not conflicts?

**Comment by nitramek** [comment]
You are right, I changed it.

**Comment by krasa** [comment]
Thanks!

**Comment by nitramek** [comment]
Pleasure, thanks for merging!

**Pull request merged**
