### PR TITLE
Redesign icons.

### PR DESCRIPTION
**Pull request by tan9**
Redesign icons to conform to the platform theme.

Before
Screenshot from 2020-05-28 09-43-16

After
Screenshot from 2020-05-28 09-37-57

### CODE REVIEW

**Comment by tan9** [comment]
@krasa would you please review this PR?

**Comment by krasa** [comment]
Thanks! 
I am not a fan of gray `m`, maybe it would be better to make it blue, even IntelliJ has it blue on some places.
image
image

**Comment by krasa** [comment]
I added a logo https://github.com/krasa/MavenHelper/commit/7dafb1728faf20d5282c2141bcc231acdf9809da

https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html

**Comment by tan9** [comment]
Hi @krasa 

How about this variant?

Screenshot from 2020-05-29 21-31-54

Almost all IntelliJ icon with modifier has only one focus (just like the JRebel icons in the bottom of screenshot), mixing blue M with green actions make the icon a bit too complicated.

**Comment by tan9** [comment]
And grey out the minor part of icon would be more consistent with the whole IntelliJ design as in https://github.com/JetBrains/intellij-community/tree/master/plugins/maven/src/main/resources/images :


Screenshot from 2020-05-29 22-06-43

**Comment by krasa** [comment]
Yes, that looks better, that gray has better contrast than green.

**Comment by tan9** [comment]
I issued #56 to include the mentioned modification.

**Pull request merged**
